ALTER TABLE "User" ADD COLUMN "password" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "User"
SET "role" = CASE
    WHEN UPPER("role") = 'ADMIN' THEN 'ADMIN'
    ELSE 'POS'
END;

ALTER TABLE "Sale" ADD COLUMN "createdById" INTEGER;

CREATE INDEX IF NOT EXISTS "Sale_createdById_idx" ON "Sale"("createdById");
